version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TABLE_NAME=mtp_app
      - DEV_MODE=true
      - AWS_REGION=us-east-1
    ports:
      - "9000:8080"
    # For local testing with DynamoDB Local
    # volumes:
    #   - ./:/var/task

